name: jaspr_grab_example
description: An example app of jaspr_grab.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  jaspr: ^0.10.0
  jaspr_grab:
    path: ..

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.6
  jaspr_builder: ^0.10.0
  lints: ^6.0.0
