name: jaspr_grab_example
description: An example app of jaspr_grab.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  jaspr: ^0.21.2
  jaspr_grab:
    path: ..

dev_dependencies:
  build_runner: ^2.8.0
  build_web_compilers: ^4.2.4
  jaspr_builder: ^0.21.2
  lints: ^6.0.0

jaspr:
  mode: client
