name: jaspr_grab_example
description: An example app of jaspr_grab.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  jaspr: ^0.2.0+4
  jaspr_grab:
    path: ..

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  lints: ^2.0.1
  webdev: ^2.7.12
