name: jaspr_grab_example
description: An example app of jaspr_grab.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.5.0
  jaspr_grab:
    path: ..

dev_dependencies:
  build_runner: ^2.4.5
  build_web_compilers: ^4.0.3
  lints: ^2.1.1
  webdev: ^3.0.5
