name: jaspr_grab
description: A package for jaspr providing mixins and extension methods to trigger a rebuild on change in a Listenable (ChangeNotifier, ValueNotifier, etc).
publish_to: 'none'
version: 0.2.0
homepage: https://github.com/kaboc/jaspr_grab

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  jaspr: ^0.3.0

dev_dependencies:
  jaspr_test: ^0.3.0
  lints: ^2.0.1
