name: jaspr_grab
description: A package for jaspr providing mixins and extension methods to trigger a rebuild on change in a Listenable (ChangeNotifier, ValueNotifier, etc).
publish_to: 'none'
version: 0.3.0
homepage: https://github.com/kaboc/jaspr_grab

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.5.0

dev_dependencies:
  jaspr_test: ^0.5.0
  lints: ^2.1.1
